const itemsDatabase = [
    {
        id: 101,
        imgSrc: "Img-Assets/library/book-thumbnail01.png",
        title: "Meaning of salary under different provisions of Income Tax Act 1961 | Relavent for CA Inter | Compiled by Karan Kushwaha",
        priceActive: "Free",
        priceNonActive: "₹299",
        description: "<h1>Meaning of Salary under Different Provisions of Income Tax Act 1961</h1><h2>Relevant for CA Inter | Compiled by Karan Kushwaha</h2><p>This book is a comprehensive guide to understanding the meaning of 'Salary' under various provisions of the <strong>Income Tax Act, 1961</strong>. The provisions and definitions of salary can often be confusing, especially for CA Intermediate students, and this book aims to simplify and clarify these concepts. Whether you're preparing for your <strong>CA Intermediate</strong> exams or looking for a quick reference guide, this book will help you get a clearer understanding of:</p><ul><li>The various components of salary as per the Income Tax Act</li><li>Taxability of salary income under different sections</li><li>Deductions and exemptions available for salary earners</li><li>Special provisions applicable to salary in different circumstances</li><li>Case studies and examples for better understanding</li></ul><p>Compiled by <strong>Karan Kushwaha</strong>, this summary book is designed to help you prepare efficiently for your CA Intermediate exams and gain a deeper understanding of taxation concepts related to salary. With clear explanations and relevant examples, this book will guide you through the complexities of the Income Tax Act.</p><h3>Key Features:</h3><ul><li>Easy-to-understand explanations</li><li>Comprehensive coverage of relevant provisions</li><li>Relevant for CA Intermediate examination</li><li>Includes practical examples and case studies</li><li>Concise yet thorough summary for effective learning</li></ul><p>Prepare with confidence for your CA Intermediate exam by mastering the crucial aspects of salary taxation with this guide!</p>"
    },
    {
        id: 102,
        imgSrc: "Img-Assets/library/book-thumbnail02.png",
        title: "CA Inter FM Formula HandBook | Compilation of all Formulas of Financial Management",
        priceActive: "Free",
        priceNonActive: "₹299",
        description: "<h1>Your Ultimate Guide to CA Intermediate FM Formulas</h1><p><strong>The Financial Management Formulae Handbook</strong> is a concise and exam-focused reference book designed for <strong>CA Intermediate students</strong>. It compiles all essential formulas from the <strong>Financial Management (FM) syllabus</strong> in a structured, easy-to-revise format.</p><h2>Key Features</h2><ul><li><span class='highlight'>Complete Formula Coverage</span> – Includes every crucial FM formula in one place.</li><li><span class='highlight'>Topic-Wise Organization</span> – Arranged <strong>chapter-wise</strong> for quick access.</li><li><span class='highlight'>Conceptual Clarity</span> – Provides brief explanations alongside formulas.</li><li><span class='highlight'>Quick Revision Format</span> – Ideal for last-minute exam prep.</li><li><span class='highlight'>Memory Aids & Shortcuts</span> – Enhances retention with mnemonics.</li><li><span class='highlight'>Practical Examples</span> – Demonstrates real-world application of formulas.</li></ul><h2>Topics Covered</h2><ul><li><strong>Time Value of Money</strong></li><li><strong>Capital Budgeting Techniques</strong> (NPV, IRR, Payback, etc.)</li><li><strong>Leverage & Cost of Capital</strong></li><li><strong>Dividend Decisions & Capital Structure</strong></li><li><strong>Working Capital Management</strong></li><li><strong>Financial Ratios & Statement Analysis</strong></li><li>…and many more essential FM concepts!</li></ul><p>This book is a <strong>must-have for CA Intermediate aspirants</strong> looking for a structured, easy-to-use, and efficient revision tool to <strong>boost exam performance</strong>.</p><h2>📢 Master FM Formulas – Ace Your CA Intermediate Exam! 🚀</h2>"
    },
    {
        id: 103,
        imgSrc: "Img-Assets/library/RTP-MTP-PYQ-MASTER-FOLDER.png",
        title: "CA Inter RTP-MTP-PYQ Master Folder | RTP, MTP &PYQ of May 2024 to May 2025 | CA Inter all PYQ | ICAI MTP, RTP, PYQ",
        priceActive: "Free",
        priceNonActive: "₹499",
        description: "<h1>CA Inter RTP-MTP-PYQ Master Folder</h1><h2>RTP, MTP & PYQ of May 2024 to May 2025 | CA Inter All PYQ | ICAI MTP, RTP, PYQ</h2><p>Prepare for your <strong>CA Intermediate</strong> exams with the ultimate resource – the <strong>CA Inter RTP-MTP-PYQ Master Folder</strong>. This comprehensive collection includes all the essential <strong>RTP (Revision Test Papers)</strong>, <strong>MTP (Mock Test Papers)</strong>, and <strong>PYQ (Past Year Questions)</strong> for the May 2024 to May 2025 examination cycle.</p><p>This folder is meticulously compiled to provide you with the most up-to-date and relevant materials for your exam preparation. It includes:</p><ul><li>Complete set of <strong>RTPs</strong> for the May 2024 and May 2025 CA Intermediate exams</li><li>All available <strong>MTPs</strong> from ICAI for mock practice and self-assessment</li><li>Comprehensive collection of <strong>PYQs</strong> from previous years to ensure thorough exam practice</li><li>Solutions and detailed explanations to help you understand the approach to solving questions</li><li>Exam-specific strategies and tips for tackling RTP, MTP, and PYQ papers</li></ul><p>This master folder is specifically designed for CA Inter students to give them the tools they need to succeed in their exams. Whether you're revising, practicing, or testing your knowledge, the <strong>CA Inter RTP-MTP-PYQ Master Folder</strong> has got you covered.</p><h3>Key Features:</h3><ul><li>All <strong>ICAI RTP, MTP, and PYQs</strong> for May 2024 and May 2025</li><li>Solutions to enhance understanding and improve problem-solving techniques</li><li>Concise yet comprehensive collection for effective revision</li><li>Perfect for last-minute practice and exam preparation</li><li>Designed to boost your confidence in approaching exam questions</li></ul><p>Gain an edge in your <strong>CA Intermediate</strong> exams with this all-in-one resource. Equip yourself with the practice materials that matter the most!</p>"
    }
];

// Export the database for use in other JS files
if (typeof module !== "undefined") {
    module.exports = itemsDatabase;
}
